// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public protocol SelectionSet: ApolloAPI.SelectionSet & ApolloAPI.RootSelectionSet
where Schema == GithubXAPI.SchemaMetadata {}

public protocol InlineFragment: ApolloAPI.SelectionSet & ApolloAPI.InlineFragment
where Schema == GithubXAPI.SchemaMetadata {}

public protocol MutableSelectionSet: ApolloAPI.MutableRootSelectionSet
where Schema == GithubXAPI.SchemaMetadata {}

public protocol MutableInlineFragment: ApolloAPI.MutableSelectionSet & ApolloAPI.InlineFragment
where Schema == GithubXAPI.SchemaMetadata {}

public enum SchemaMetadata: ApolloAPI.SchemaMetadata {
  public static let configuration: any ApolloAPI.SchemaConfiguration.Type = SchemaConfiguration.self

  public static func objectType(forTypename typename: String) -> ApolloAPI.Object? {
    switch typename {
    case "Query": return GithubXAPI.Objects.Query
    case "User": return GithubXAPI.Objects.User
    case "Bot": return GithubXAPI.Objects.Bot
    case "AddedToMergeQueueEvent": return GithubXAPI.Objects.AddedToMergeQueueEvent
    case "AddedToProjectEvent": return GithubXAPI.Objects.AddedToProjectEvent
    case "App": return GithubXAPI.Objects.App
    case "AssignedEvent": return GithubXAPI.Objects.AssignedEvent
    case "AutoMergeDisabledEvent": return GithubXAPI.Objects.AutoMergeDisabledEvent
    case "AutoMergeEnabledEvent": return GithubXAPI.Objects.AutoMergeEnabledEvent
    case "AutoRebaseEnabledEvent": return GithubXAPI.Objects.AutoRebaseEnabledEvent
    case "AutoSquashEnabledEvent": return GithubXAPI.Objects.AutoSquashEnabledEvent
    case "AutomaticBaseChangeFailedEvent": return GithubXAPI.Objects.AutomaticBaseChangeFailedEvent
    case "AutomaticBaseChangeSucceededEvent": return GithubXAPI.Objects.AutomaticBaseChangeSucceededEvent
    case "BaseRefChangedEvent": return GithubXAPI.Objects.BaseRefChangedEvent
    case "BaseRefDeletedEvent": return GithubXAPI.Objects.BaseRefDeletedEvent
    case "BaseRefForcePushedEvent": return GithubXAPI.Objects.BaseRefForcePushedEvent
    case "Blob": return GithubXAPI.Objects.Blob
    case "Commit": return GithubXAPI.Objects.Commit
    case "Discussion": return GithubXAPI.Objects.Discussion
    case "Issue": return GithubXAPI.Objects.Issue
    case "PullRequest": return GithubXAPI.Objects.PullRequest
    case "CommitComment": return GithubXAPI.Objects.CommitComment
    case "DiscussionComment": return GithubXAPI.Objects.DiscussionComment
    case "GistComment": return GithubXAPI.Objects.GistComment
    case "IssueComment": return GithubXAPI.Objects.IssueComment
    case "PullRequestReview": return GithubXAPI.Objects.PullRequestReview
    case "CommitCommentThread": return GithubXAPI.Objects.CommitCommentThread
    case "DependabotUpdate": return GithubXAPI.Objects.DependabotUpdate
    case "DiscussionCategory": return GithubXAPI.Objects.DiscussionCategory
    case "PinnedDiscussion": return GithubXAPI.Objects.PinnedDiscussion
    case "PullRequestCommitCommentThread": return GithubXAPI.Objects.PullRequestCommitCommentThread
    case "PullRequestReviewComment": return GithubXAPI.Objects.PullRequestReviewComment
    case "TeamDiscussion": return GithubXAPI.Objects.TeamDiscussion
    case "CheckRun": return GithubXAPI.Objects.CheckRun
    case "StatusContext": return GithubXAPI.Objects.StatusContext
    case "ClosedEvent": return GithubXAPI.Objects.ClosedEvent
    case "ConvertToDraftEvent": return GithubXAPI.Objects.ConvertToDraftEvent
    case "CrossReferencedEvent": return GithubXAPI.Objects.CrossReferencedEvent
    case "Gist": return GithubXAPI.Objects.Gist
    case "Repository": return GithubXAPI.Objects.Repository
    case "Organization": return GithubXAPI.Objects.Organization
    case "Enterprise": return GithubXAPI.Objects.Enterprise
    case "Team": return GithubXAPI.Objects.Team
    case "Topic": return GithubXAPI.Objects.Topic
    case "Mannequin": return GithubXAPI.Objects.Mannequin
    case "MergedEvent": return GithubXAPI.Objects.MergedEvent
    case "Milestone": return GithubXAPI.Objects.Milestone
    case "PullRequestCommit": return GithubXAPI.Objects.PullRequestCommit
    case "ReadyForReviewEvent": return GithubXAPI.Objects.ReadyForReviewEvent
    case "Release": return GithubXAPI.Objects.Release
    case "RepositoryTopic": return GithubXAPI.Objects.RepositoryTopic
    case "ReviewDismissedEvent": return GithubXAPI.Objects.ReviewDismissedEvent
    case "TeamDiscussionComment": return GithubXAPI.Objects.TeamDiscussionComment
    case "Workflow": return GithubXAPI.Objects.Workflow
    case "WorkflowRun": return GithubXAPI.Objects.WorkflowRun
    case "WorkflowRunFile": return GithubXAPI.Objects.WorkflowRunFile
    case "RepositoryVulnerabilityAlert": return GithubXAPI.Objects.RepositoryVulnerabilityAlert
    case "Project": return GithubXAPI.Objects.Project
    case "ProjectV2": return GithubXAPI.Objects.ProjectV2
    case "Tag": return GithubXAPI.Objects.Tag
    case "Tree": return GithubXAPI.Objects.Tree
    case "BranchProtectionRule": return GithubXAPI.Objects.BranchProtectionRule
    case "BypassForcePushAllowance": return GithubXAPI.Objects.BypassForcePushAllowance
    case "BypassPullRequestAllowance": return GithubXAPI.Objects.BypassPullRequestAllowance
    case "CWE": return GithubXAPI.Objects.CWE
    case "CheckSuite": return GithubXAPI.Objects.CheckSuite
    case "CodeOfConduct": return GithubXAPI.Objects.CodeOfConduct
    case "CommentDeletedEvent": return GithubXAPI.Objects.CommentDeletedEvent
    case "Comparison": return GithubXAPI.Objects.Comparison
    case "ConnectedEvent": return GithubXAPI.Objects.ConnectedEvent
    case "ConvertedNoteToIssueEvent": return GithubXAPI.Objects.ConvertedNoteToIssueEvent
    case "ConvertedToDiscussionEvent": return GithubXAPI.Objects.ConvertedToDiscussionEvent
    case "DemilestonedEvent": return GithubXAPI.Objects.DemilestonedEvent
    case "DependencyGraphManifest": return GithubXAPI.Objects.DependencyGraphManifest
    case "DeployKey": return GithubXAPI.Objects.DeployKey
    case "DeployedEvent": return GithubXAPI.Objects.DeployedEvent
    case "Deployment": return GithubXAPI.Objects.Deployment
    case "DeploymentEnvironmentChangedEvent": return GithubXAPI.Objects.DeploymentEnvironmentChangedEvent
    case "DeploymentReview": return GithubXAPI.Objects.DeploymentReview
    case "DeploymentStatus": return GithubXAPI.Objects.DeploymentStatus
    case "DisconnectedEvent": return GithubXAPI.Objects.DisconnectedEvent
    case "DiscussionPoll": return GithubXAPI.Objects.DiscussionPoll
    case "DiscussionPollOption": return GithubXAPI.Objects.DiscussionPollOption
    case "DraftIssue": return GithubXAPI.Objects.DraftIssue
    case "EnterpriseAdministratorInvitation": return GithubXAPI.Objects.EnterpriseAdministratorInvitation
    case "EnterpriseIdentityProvider": return GithubXAPI.Objects.EnterpriseIdentityProvider
    case "EnterpriseMemberInvitation": return GithubXAPI.Objects.EnterpriseMemberInvitation
    case "EnterpriseRepositoryInfo": return GithubXAPI.Objects.EnterpriseRepositoryInfo
    case "EnterpriseServerInstallation": return GithubXAPI.Objects.EnterpriseServerInstallation
    case "EnterpriseServerUserAccount": return GithubXAPI.Objects.EnterpriseServerUserAccount
    case "EnterpriseServerUserAccountEmail": return GithubXAPI.Objects.EnterpriseServerUserAccountEmail
    case "EnterpriseServerUserAccountsUpload": return GithubXAPI.Objects.EnterpriseServerUserAccountsUpload
    case "EnterpriseUserAccount": return GithubXAPI.Objects.EnterpriseUserAccount
    case "Environment": return GithubXAPI.Objects.Environment
    case "ExternalIdentity": return GithubXAPI.Objects.ExternalIdentity
    case "HeadRefDeletedEvent": return GithubXAPI.Objects.HeadRefDeletedEvent
    case "HeadRefForcePushedEvent": return GithubXAPI.Objects.HeadRefForcePushedEvent
    case "HeadRefRestoredEvent": return GithubXAPI.Objects.HeadRefRestoredEvent
    case "IpAllowListEntry": return GithubXAPI.Objects.IpAllowListEntry
    case "Label": return GithubXAPI.Objects.Label
    case "LabeledEvent": return GithubXAPI.Objects.LabeledEvent
    case "Language": return GithubXAPI.Objects.Language
    case "License": return GithubXAPI.Objects.License
    case "LinkedBranch": return GithubXAPI.Objects.LinkedBranch
    case "LockedEvent": return GithubXAPI.Objects.LockedEvent
    case "MarkedAsDuplicateEvent": return GithubXAPI.Objects.MarkedAsDuplicateEvent
    case "MarketplaceCategory": return GithubXAPI.Objects.MarketplaceCategory
    case "MarketplaceListing": return GithubXAPI.Objects.MarketplaceListing
    case "MemberFeatureRequestNotification": return GithubXAPI.Objects.MemberFeatureRequestNotification
    case "MembersCanDeleteReposClearAuditEntry": return GithubXAPI.Objects.MembersCanDeleteReposClearAuditEntry
    case "MembersCanDeleteReposDisableAuditEntry": return GithubXAPI.Objects.MembersCanDeleteReposDisableAuditEntry
    case "MembersCanDeleteReposEnableAuditEntry": return GithubXAPI.Objects.MembersCanDeleteReposEnableAuditEntry
    case "OauthApplicationCreateAuditEntry": return GithubXAPI.Objects.OauthApplicationCreateAuditEntry
    case "OrgOauthAppAccessApprovedAuditEntry": return GithubXAPI.Objects.OrgOauthAppAccessApprovedAuditEntry
    case "OrgOauthAppAccessBlockedAuditEntry": return GithubXAPI.Objects.OrgOauthAppAccessBlockedAuditEntry
    case "OrgOauthAppAccessDeniedAuditEntry": return GithubXAPI.Objects.OrgOauthAppAccessDeniedAuditEntry
    case "OrgOauthAppAccessRequestedAuditEntry": return GithubXAPI.Objects.OrgOauthAppAccessRequestedAuditEntry
    case "OrgOauthAppAccessUnblockedAuditEntry": return GithubXAPI.Objects.OrgOauthAppAccessUnblockedAuditEntry
    case "OrgAddBillingManagerAuditEntry": return GithubXAPI.Objects.OrgAddBillingManagerAuditEntry
    case "OrgAddMemberAuditEntry": return GithubXAPI.Objects.OrgAddMemberAuditEntry
    case "OrgBlockUserAuditEntry": return GithubXAPI.Objects.OrgBlockUserAuditEntry
    case "OrgConfigDisableCollaboratorsOnlyAuditEntry": return GithubXAPI.Objects.OrgConfigDisableCollaboratorsOnlyAuditEntry
    case "OrgConfigEnableCollaboratorsOnlyAuditEntry": return GithubXAPI.Objects.OrgConfigEnableCollaboratorsOnlyAuditEntry
    case "OrgCreateAuditEntry": return GithubXAPI.Objects.OrgCreateAuditEntry
    case "OrgDisableOauthAppRestrictionsAuditEntry": return GithubXAPI.Objects.OrgDisableOauthAppRestrictionsAuditEntry
    case "OrgDisableSamlAuditEntry": return GithubXAPI.Objects.OrgDisableSamlAuditEntry
    case "OrgDisableTwoFactorRequirementAuditEntry": return GithubXAPI.Objects.OrgDisableTwoFactorRequirementAuditEntry
    case "OrgEnableOauthAppRestrictionsAuditEntry": return GithubXAPI.Objects.OrgEnableOauthAppRestrictionsAuditEntry
    case "OrgEnableSamlAuditEntry": return GithubXAPI.Objects.OrgEnableSamlAuditEntry
    case "OrgEnableTwoFactorRequirementAuditEntry": return GithubXAPI.Objects.OrgEnableTwoFactorRequirementAuditEntry
    case "OrgInviteMemberAuditEntry": return GithubXAPI.Objects.OrgInviteMemberAuditEntry
    case "OrgInviteToBusinessAuditEntry": return GithubXAPI.Objects.OrgInviteToBusinessAuditEntry
    case "OrgRemoveBillingManagerAuditEntry": return GithubXAPI.Objects.OrgRemoveBillingManagerAuditEntry
    case "OrgRemoveMemberAuditEntry": return GithubXAPI.Objects.OrgRemoveMemberAuditEntry
    case "OrgRemoveOutsideCollaboratorAuditEntry": return GithubXAPI.Objects.OrgRemoveOutsideCollaboratorAuditEntry
    case "OrgRestoreMemberAuditEntry": return GithubXAPI.Objects.OrgRestoreMemberAuditEntry
    case "OrgRestoreMemberMembershipOrganizationAuditEntryData": return GithubXAPI.Objects.OrgRestoreMemberMembershipOrganizationAuditEntryData
    case "OrgUnblockUserAuditEntry": return GithubXAPI.Objects.OrgUnblockUserAuditEntry
    case "OrgUpdateDefaultRepositoryPermissionAuditEntry": return GithubXAPI.Objects.OrgUpdateDefaultRepositoryPermissionAuditEntry
    case "OrgUpdateMemberAuditEntry": return GithubXAPI.Objects.OrgUpdateMemberAuditEntry
    case "OrgUpdateMemberRepositoryCreationPermissionAuditEntry": return GithubXAPI.Objects.OrgUpdateMemberRepositoryCreationPermissionAuditEntry
    case "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry": return GithubXAPI.Objects.OrgUpdateMemberRepositoryInvitationPermissionAuditEntry
    case "PrivateRepositoryForkingDisableAuditEntry": return GithubXAPI.Objects.PrivateRepositoryForkingDisableAuditEntry
    case "OrgRestoreMemberMembershipRepositoryAuditEntryData": return GithubXAPI.Objects.OrgRestoreMemberMembershipRepositoryAuditEntryData
    case "PrivateRepositoryForkingEnableAuditEntry": return GithubXAPI.Objects.PrivateRepositoryForkingEnableAuditEntry
    case "RepoAccessAuditEntry": return GithubXAPI.Objects.RepoAccessAuditEntry
    case "RepoAddMemberAuditEntry": return GithubXAPI.Objects.RepoAddMemberAuditEntry
    case "RepoAddTopicAuditEntry": return GithubXAPI.Objects.RepoAddTopicAuditEntry
    case "RepoRemoveTopicAuditEntry": return GithubXAPI.Objects.RepoRemoveTopicAuditEntry
    case "RepoArchivedAuditEntry": return GithubXAPI.Objects.RepoArchivedAuditEntry
    case "RepoChangeMergeSettingAuditEntry": return GithubXAPI.Objects.RepoChangeMergeSettingAuditEntry
    case "RepoConfigDisableAnonymousGitAccessAuditEntry": return GithubXAPI.Objects.RepoConfigDisableAnonymousGitAccessAuditEntry
    case "RepoConfigDisableCollaboratorsOnlyAuditEntry": return GithubXAPI.Objects.RepoConfigDisableCollaboratorsOnlyAuditEntry
    case "RepoConfigDisableContributorsOnlyAuditEntry": return GithubXAPI.Objects.RepoConfigDisableContributorsOnlyAuditEntry
    case "RepoConfigDisableSockpuppetDisallowedAuditEntry": return GithubXAPI.Objects.RepoConfigDisableSockpuppetDisallowedAuditEntry
    case "RepoConfigEnableAnonymousGitAccessAuditEntry": return GithubXAPI.Objects.RepoConfigEnableAnonymousGitAccessAuditEntry
    case "RepoConfigEnableCollaboratorsOnlyAuditEntry": return GithubXAPI.Objects.RepoConfigEnableCollaboratorsOnlyAuditEntry
    case "RepoConfigEnableContributorsOnlyAuditEntry": return GithubXAPI.Objects.RepoConfigEnableContributorsOnlyAuditEntry
    case "RepoConfigEnableSockpuppetDisallowedAuditEntry": return GithubXAPI.Objects.RepoConfigEnableSockpuppetDisallowedAuditEntry
    case "RepoConfigLockAnonymousGitAccessAuditEntry": return GithubXAPI.Objects.RepoConfigLockAnonymousGitAccessAuditEntry
    case "RepoConfigUnlockAnonymousGitAccessAuditEntry": return GithubXAPI.Objects.RepoConfigUnlockAnonymousGitAccessAuditEntry
    case "RepoCreateAuditEntry": return GithubXAPI.Objects.RepoCreateAuditEntry
    case "RepoDestroyAuditEntry": return GithubXAPI.Objects.RepoDestroyAuditEntry
    case "RepoRemoveMemberAuditEntry": return GithubXAPI.Objects.RepoRemoveMemberAuditEntry
    case "TeamAddRepositoryAuditEntry": return GithubXAPI.Objects.TeamAddRepositoryAuditEntry
    case "OrgRestoreMemberMembershipTeamAuditEntryData": return GithubXAPI.Objects.OrgRestoreMemberMembershipTeamAuditEntryData
    case "TeamAddMemberAuditEntry": return GithubXAPI.Objects.TeamAddMemberAuditEntry
    case "TeamChangeParentTeamAuditEntry": return GithubXAPI.Objects.TeamChangeParentTeamAuditEntry
    case "TeamRemoveMemberAuditEntry": return GithubXAPI.Objects.TeamRemoveMemberAuditEntry
    case "TeamRemoveRepositoryAuditEntry": return GithubXAPI.Objects.TeamRemoveRepositoryAuditEntry
    case "RepositoryVisibilityChangeDisableAuditEntry": return GithubXAPI.Objects.RepositoryVisibilityChangeDisableAuditEntry
    case "RepositoryVisibilityChangeEnableAuditEntry": return GithubXAPI.Objects.RepositoryVisibilityChangeEnableAuditEntry
    case "MentionedEvent": return GithubXAPI.Objects.MentionedEvent
    case "MergeQueue": return GithubXAPI.Objects.MergeQueue
    case "MergeQueueEntry": return GithubXAPI.Objects.MergeQueueEntry
    case "MigrationSource": return GithubXAPI.Objects.MigrationSource
    case "MilestonedEvent": return GithubXAPI.Objects.MilestonedEvent
    case "MovedColumnsInProjectEvent": return GithubXAPI.Objects.MovedColumnsInProjectEvent
    case "OIDCProvider": return GithubXAPI.Objects.OIDCProvider
    case "OrganizationIdentityProvider": return GithubXAPI.Objects.OrganizationIdentityProvider
    case "OrganizationInvitation": return GithubXAPI.Objects.OrganizationInvitation
    case "OrganizationMigration": return GithubXAPI.Objects.OrganizationMigration
    case "Package": return GithubXAPI.Objects.Package
    case "PackageFile": return GithubXAPI.Objects.PackageFile
    case "PackageTag": return GithubXAPI.Objects.PackageTag
    case "PackageVersion": return GithubXAPI.Objects.PackageVersion
    case "PinnedEnvironment": return GithubXAPI.Objects.PinnedEnvironment
    case "PinnedEvent": return GithubXAPI.Objects.PinnedEvent
    case "PinnedIssue": return GithubXAPI.Objects.PinnedIssue
    case "ProjectCard": return GithubXAPI.Objects.ProjectCard
    case "ProjectColumn": return GithubXAPI.Objects.ProjectColumn
    case "ProjectV2Field": return GithubXAPI.Objects.ProjectV2Field
    case "ProjectV2IterationField": return GithubXAPI.Objects.ProjectV2IterationField
    case "ProjectV2SingleSelectField": return GithubXAPI.Objects.ProjectV2SingleSelectField
    case "ProjectV2Item": return GithubXAPI.Objects.ProjectV2Item
    case "ProjectV2ItemFieldDateValue": return GithubXAPI.Objects.ProjectV2ItemFieldDateValue
    case "ProjectV2ItemFieldIterationValue": return GithubXAPI.Objects.ProjectV2ItemFieldIterationValue
    case "ProjectV2ItemFieldNumberValue": return GithubXAPI.Objects.ProjectV2ItemFieldNumberValue
    case "ProjectV2ItemFieldSingleSelectValue": return GithubXAPI.Objects.ProjectV2ItemFieldSingleSelectValue
    case "ProjectV2ItemFieldTextValue": return GithubXAPI.Objects.ProjectV2ItemFieldTextValue
    case "ProjectV2StatusUpdate": return GithubXAPI.Objects.ProjectV2StatusUpdate
    case "ProjectV2View": return GithubXAPI.Objects.ProjectV2View
    case "ProjectV2Workflow": return GithubXAPI.Objects.ProjectV2Workflow
    case "PublicKey": return GithubXAPI.Objects.PublicKey
    case "PullRequestReviewThread": return GithubXAPI.Objects.PullRequestReviewThread
    case "PullRequestThread": return GithubXAPI.Objects.PullRequestThread
    case "Push": return GithubXAPI.Objects.Push
    case "PushAllowance": return GithubXAPI.Objects.PushAllowance
    case "Reaction": return GithubXAPI.Objects.Reaction
    case "Ref": return GithubXAPI.Objects.Ref
    case "ReferencedEvent": return GithubXAPI.Objects.ReferencedEvent
    case "ReleaseAsset": return GithubXAPI.Objects.ReleaseAsset
    case "RemovedFromMergeQueueEvent": return GithubXAPI.Objects.RemovedFromMergeQueueEvent
    case "RemovedFromProjectEvent": return GithubXAPI.Objects.RemovedFromProjectEvent
    case "RenamedTitleEvent": return GithubXAPI.Objects.RenamedTitleEvent
    case "ReopenedEvent": return GithubXAPI.Objects.ReopenedEvent
    case "RepositoryInvitation": return GithubXAPI.Objects.RepositoryInvitation
    case "RepositoryMigration": return GithubXAPI.Objects.RepositoryMigration
    case "RepositoryRule": return GithubXAPI.Objects.RepositoryRule
    case "RepositoryRuleset": return GithubXAPI.Objects.RepositoryRuleset
    case "RepositoryRulesetBypassActor": return GithubXAPI.Objects.RepositoryRulesetBypassActor
    case "ReviewDismissalAllowance": return GithubXAPI.Objects.ReviewDismissalAllowance
    case "ReviewRequest": return GithubXAPI.Objects.ReviewRequest
    case "ReviewRequestRemovedEvent": return GithubXAPI.Objects.ReviewRequestRemovedEvent
    case "ReviewRequestedEvent": return GithubXAPI.Objects.ReviewRequestedEvent
    case "SavedReply": return GithubXAPI.Objects.SavedReply
    case "SecurityAdvisory": return GithubXAPI.Objects.SecurityAdvisory
    case "SponsorsActivity": return GithubXAPI.Objects.SponsorsActivity
    case "SponsorsListing": return GithubXAPI.Objects.SponsorsListing
    case "SponsorsListingFeaturedItem": return GithubXAPI.Objects.SponsorsListingFeaturedItem
    case "SponsorsTier": return GithubXAPI.Objects.SponsorsTier
    case "Sponsorship": return GithubXAPI.Objects.Sponsorship
    case "SponsorshipNewsletter": return GithubXAPI.Objects.SponsorshipNewsletter
    case "Status": return GithubXAPI.Objects.Status
    case "StatusCheckRollup": return GithubXAPI.Objects.StatusCheckRollup
    case "SubscribedEvent": return GithubXAPI.Objects.SubscribedEvent
    case "TransferredEvent": return GithubXAPI.Objects.TransferredEvent
    case "UnassignedEvent": return GithubXAPI.Objects.UnassignedEvent
    case "UnlabeledEvent": return GithubXAPI.Objects.UnlabeledEvent
    case "UnlockedEvent": return GithubXAPI.Objects.UnlockedEvent
    case "UnmarkedAsDuplicateEvent": return GithubXAPI.Objects.UnmarkedAsDuplicateEvent
    case "UnpinnedEvent": return GithubXAPI.Objects.UnpinnedEvent
    case "UnsubscribedEvent": return GithubXAPI.Objects.UnsubscribedEvent
    case "UserBlockedEvent": return GithubXAPI.Objects.UserBlockedEvent
    case "UserContentEdit": return GithubXAPI.Objects.UserContentEdit
    case "UserList": return GithubXAPI.Objects.UserList
    case "UserStatus": return GithubXAPI.Objects.UserStatus
    case "VerifiableDomain": return GithubXAPI.Objects.VerifiableDomain
    case "Mutation": return GithubXAPI.Objects.Mutation
    case "CreateRepositoryPayload": return GithubXAPI.Objects.CreateRepositoryPayload
    default: return nil
    }
  }
}

public enum Objects {}
public enum Interfaces {}
public enum Unions {}
