# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GraphQLInIOSWithSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GraphQLInIOSWithSwiftUI
  pod 'Apollo', '~> 0.50.0'
pod "Apollo/SQLite"
pod "Apollo/WebSocket"


end
