# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoJUSPAY' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demoJUSPAY
# Adding Hyper SDK dependecy
  # block:start:adding-hyper-sdk-pod
  pod 'HyperSDK', '2.1.31'
  # block:end:adding-hyper-sdk-pod

end

# Adding Hyper SDK dependecy
# block:start:adding-plugin-installation-script
post_install do |installer|
 fuse_path = "./Pods/HyperSDK/Fuse.rb"
 clean_assets = true # Pass true to re-download all the assets
 if File.exist?(fuse_path)
   if system("ruby", fuse_path.to_s, clean_assets.to_s)
   end
 end
end
# block:end:adding-plugin-installation-script